# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bundle News iOS Challange' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bundle News iOS Challange

    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
    pod 'Alamofire', '~> 5.0'
    pod 'KFSwiftImageLoader'
    pod 'PKHUD', '~> 5.0'

  target 'Bundle News iOS ChallangeTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '~> 5'
    pod 'RxTest', '~> 5'
  end

  target 'Bundle News iOS ChallangeUITests' do
    # Pods for testing
  end

end
